### PR TITLE
Add FLEX & BISON based lexer & parser

### PR DESCRIPTION
**Pull request by mmamayka**
Parser & lexer should be able to parse specified file format in proper way, find out lexical & grammar error. Usage examples can be found in 'lexer.py' & 'parser.py' files under the 'main' condition.

### CODE REVIEW

**Comment by alexmangushev** [comment]
Add check for 1 or -1 in ORDER section for each element

**Comment by alexmangushev** [comment]
Add message with error in data

**Comment by alexmangushev** [comment]
Add check for destination point equal 0 0

**Comment by alexmangushev** [comment]
Add check for count of elements in DATA section and ORDER section

**Comment by alexmangushev** [comment]
Add check for "/" in end of section

**Comment by alexmangushev** [comment]
Add support negative numbers for path block's cost in DATA section

**Comment by mmamayka** [comment]
This MR contains only parser & lexer implementation, thus all unrelated checks will be added in some other MR. Please, create an issue next time.

I've supported negative and floating point numbers, so all test you have added works fine now. Also error messages was made a bit more user friendly.

**Pull request merged**
